version: '3.9'
services:
  hapi-server:
    image: kvalitetsit/hjemmebehandling-hapi-fhir-server:dev
    environment:
      - spring.datasource.url=jdbc:mysql://mariadb:3306/hapi
      - spring.datasource.username=hapi
      - spring.datasource.password=hapi
    ports:
      - 8082:8080
    depends_on:
      - mariadb
  #  healthcheck:
  #    test: [ "CMD", "curl", "-f", "http://localhost:8080/fhir/metadata" ]
  #    interval: 1m
  #    timeout: 10s
  #    retries: 3
  #    start_period: 40s
#
  #hapi-server-initializer:
  #  image: kvalitetsit/hjemmebehandling-data-initializer:latest
  #  depends_on:
  #    hapi-server:
  #      condition: service_healthy
  #  environment:
  #    - init_test_data=true


  mariadb:
    image: mariadb:10.7
    environment:
      - MARIADB_USER=hapi
      - MARIADB_PASSWORD=hapi
      - MARIADB_ROOT_PASSWORD=hapi
      - MARIADB_DATABASE=hapi
    ports:
      - 3306:3306